name: Playwright Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    # Install backend dependencies
    - name: Install Backend Dependencies
      run: |
        cd src
        npm install

    # Start backend in background
    - name: Start Backend
      run: |
        cd src
        node app.js &
    
    # Wait for backend to start
    - name: Wait for backend
      run: npx wait-on http://localhost:3000

    # Install Playwright
    - name: Install Playwright
      run: |
        cd qa-automation
        npm install
        npx playwright install --with-deps

    # Run tests
    - name: Run Playwright Tests
      run: |
        cd qa-automation
        npx playwright test